### PR TITLE
CMAKE Build

### PR DESCRIPTION
**Pull request by Angelyr**
Adds CMAKE files used for compiling.
Tested on Pelrmutter and SCOREC.

### CODE REVIEW

**Comment by jacobmerson** [comment]
@nferraro as discussed, we put together this pull request for converting the fusion-io build to cmake to make it easier to link/integrate with other packages and as a starting point for integrating with PCMS.

Please let us know if there are additional things that are needed for this.

**Comment by nferraro** [comment]
Thanks!  I'm not very familiar with cmake.  When I try to build this PR using cmake on perlmutter, 
I'm getting the following error:
nvfortran-Error-Unknown switch: -fdefault-real-8
nvfortran-Error-Unknown switch: -fimplicit-none

**Comment by Angelyr** [comment]
Here are the commands that you need to compile on perlmutter. (Note that you have to run them from outside the fusion-io directory):
```
module load cray-hdf5

cmake -S fusion-io -B build-fusion-io \
    -DCMAKE_INSTALL_PREFIX=build-fusion-io/install \
    -DBUILD_TESTING=on

cmake --build build-fusion-io --target install -j8
```

**Comment by jacobmerson** [comment]
@nferraro what compiler are you using?

**Comment by changliu777** [comment]
@jacobmerson This is Chang Liu from PPPL. I developed the CMake build files for M3D-C1 and I am also working on Fusion-IO build file. The purpose is to make it work with Spack. I have pushed my build files to a new branch "cmake_changliu". I think your pull request provides better implementation and is almost ready to merge. I just have a few requests,

1. Instead of writing presets files for different machines (which is hard as we need to support many machines), can you write different Fortran options for different compilers? We need to support GNU, Intel, NVHPC and Cray (mostly for Frontier). You can check my CMakeLists.txt.
2. I noticed that you have Python module compiled, but there is no installation instruction for that. The Python module should be installed into a different library path determined by the Python version used. In addition, the fpy.py file also needs to be installed.
4. Can you add some CMake switches? like ENABLE_PYTHON, ENABLE_TRACE? This can make developing Spack package file much easier.

**Comment by jacobmerson** [comment]
@changliu777, thanks for the comments. @Angelyr has been doing a great job getting this off the ground.

>     1. Instead of writing presets files for different machines (which is hard as we need to support many machines), can you write different Fortran options for different compilers? We need to support GNU, Intel, NVHPC and Cray (mostly for Frontier). You can check my CMakeLists.txt.
> 
I believe CMakePresets.json can be set up to automatically select a preset based on hostname or possibly compiler. Although we may need to have the user specify the preset by the compiler. My preference for the presets file is that it is much easier to extend for new systems or new compiler versions that do not support the same flags. Let's see if we can iterate a bit to see if we can make a version of that which seems good to you. If not, we can implement with generator expressions (or if statements) in the `CMakeLists.txt` .

In my mind the issue with if statements for compilers is that often flags get put there which need to be modified or removed for new compiler versions or different system setups. Then the user has to go digging through the `CMakeLists.txt` to find where the flags are added.

>     2. I noticed that you have Python module compiled, but there is no installation instruction for that. The Python module should be installed into a different library path determined by the Python version used. In addition, the fpy.py file also needs to be installed.

Can @changliu777 or @nferraro say more about the use case for this? For the python wrappers that I build with `CMake` I usually just have the user point `PYTHONPATH` to the directory with the `.so` and module files. Spack should support this with`extends('python')`.

We will add `fpy.py` to the installation.

>     3. Can you add some CMake switches? like ENABLE_PYTHON, ENABLE_TRACE? This can make developing Spack package file much easier.

Yes! Great catch. @Angelyr any variables like this should be prefixed with `FUSIONIO_` or some other package specific prefix.

**Comment by changliu777** [comment]
@jacobmerson @Angelyr Thank you for the answers.

1. I was not familiar with CMakePresets.json before and after reading your comments I think it is indeed a good idea to use it. We can set a hierarchical structure in it, different presets for different compilers or machines. For new machines the user can create a new preset inheriting settings from a previous one. My only concern is that whether this can work well with Spack, as we want to make Spack package.py as general as possible and not depending on any machine-dependent settings.
2. I think it is OK to ask the user to set the PYTHONPATH variable. For Spack we want user to be able to use the python library just after installing it. Spack only sets PYTHONPATH to the site-packages directory of the current installed python, so it is better to install the python library (.so file) and other python scripts to this directory. This can be done by passing "python_platlib" to the CMake install script in package.py. You can find an example at https://github.com/spack/spack/blob/6a6c2959384b8242acf63e9f3f7ed6a2f38b6e1d/var/spack/repos/builtin/packages/damaris/package.py#L10

**Comment by jacobmerson** [comment]
That's a good point about spack integration. It could potentially cause a need for duplication in the flags if we had to include them both in the `CMakePresents.json` file as well as in the spack `package.py` as `CMAKE_CXX_FLAGS`

**Comment by jacobmerson** [comment]
I asked about this on the slack channel and I'm sharing the screenshots below. Ryan Krattiger suggests that we can pas the `--preset` argument to `cmake_args`. This seems like it might be a reasonable way to handle this. But, it's a new modality for me, so I think we should try it out and see if we think it's a scalable solution.

image
image

**Comment by Angelyr** [comment]
@changliu777 I've made the changes that you requested. Feel free to take a look and let me know if there are any other changes. 
I've removed the `CMakePresets.json` since the flags I was testing were required for compiling. In the future I believe it will be better to reserve `CMakePresets.json` for optional flags.

**Comment by jacobmerson** [comment]
@changliu777 I think this is ready for your review.

**Comment by changliu777** [comment]
@Angelyr @jacobmerson 

Thank you. I got the following error in the make install stage

```
CMake Error at fusion_io/cmake_install.cmake:114 (file):
  file INSTALL cannot find
  "/home/liuchang/fusion-io4/fusion_io/fusionio-config.cmake": No such file
  or directory.
Call Stack (most recent call first):
  cmake_install.cmake:52 (include)
```

I think CMake is looking for `fusionio-config.cmake` but it is not available in the directory.

**Comment by changliu777** [comment]
@jacobmerson @Angelyr Thank you for the answers.

The CMake files can build and install. However, the Fortran module file in fusion_io directory, through generated, are not installed to the INCLUDE directory.

These module files are necessary to build Fortran code depending on FusionIO.

**Comment by changliu777** [comment]
@Angelyr Right now the `fio_py.so` and `fpy.py` files are not installed to the installation path, but to the compilation directory. This might be OK to use if we ask the user to set the `PYTHONPATH` manually, but it will not work for installation in Spack. I suggest to the following

```
  if(DEFINED PYTHON_MODULE_INSTALL_PATH)
    install(FILES fpy.py
          DESTINATION ${PYTHON_MODULE_INSTALL_PATH})
    install(TARGETS fio_py
          DESTINATION ${PYTHON_MODULE_INSTALL_PATH})
 endif()
  
```

**Comment by Angelyr** [comment]
@changliu777 Thanks for the sample code. I made a similar change.

**Comment by jacobmerson** [comment]
I didn't know about that `PYTHON_MODULE_INSTALL_PATH`. That's super useful.

**Comment by changliu777** [comment]
@jacobmerson FYI, `PYTHON_MODULE_INSTALL_PATH` is not an official name from CMake or Python, but it is used by some Spack package maintainers (and some use a different variable name).

**Comment by changliu777** [comment]
@Angelyr Can you please add the installation of excutables `trace` and `plot_dr` to the `bin` directory? Like this

```
install(TARGETS trace plot_dr
   RUNTIME DESTINATION "bin"
)
```

**Comment by Angelyr** [comment]
@changliu777 Ok, I have made that change.

**Comment by jacobmerson** [comment]
@Angelyr you should use `BINDIR` from `GNUInstallDirs` rather than hardcoding `bin`

**Comment by changliu777** [comment]
@Angelyr Great. It works well for GNU compiler now.

To avoid issues @nferraro met using a different compiler, can you add more conditional statement for Fortran compilers setting the size of the real type? like this

```
if (CMAKE_Fortran_COMPILER_ID STREQUAL "Cray")
    set(CMAKE_Fortran_FLAGS "-s real64")
elseif (CMAKE_Fortran_COMPILER_ID STREQUAL "GNU")
    set(CMAKE_Fortran_FLAGS "-fdefault-real-8")
elseif (CMAKE_Fortran_COMPILER_ID STREQUAL "Intel")
    set(CMAKE_Fortran_FLAGS "-real-size 64")
elseif (CMAKE_Fortran_COMPILER_ID STREQUAL "NVHPC")
    set(CMAKE_Fortran_FLAGS "-r8")
else()
    set(CMAKE_Fortran_FLAGS "-r8")
endif()
```

**Comment by Angelyr** [comment]
@changliu777 
I made the change, but I haven't tested it. Were you planning on testing it?

**Comment by changliu777** [comment]
@Angelyr I tested it using the Intel compiler. Two issues,

1. Please change the if statement from `STREQUAL` back to `MATCHES`. The new Intel compiler will be identified to IntelLLVM instead of Intel. So I think `MATCHES` works better since it can match both the old and the new versions.
2. In m3dc1_lib/CMakeLists.txt, please add the following at the end,
```
set_property(TARGET m3dc1_fortran_test PROPERTY LINKER_LANGUAGE Fortran)
```
This will ensure CMake to use Fortran compiler to link the code. Otherwise it will use a C++ compiler to do the job, and gives an error when using Intel or NVHPC compilers.

**Comment by Angelyr** [comment]
@changliu777 Ok done.

**Pull request merged**
